import { config } from 'dotenv';
import { PrismaClient } from '@prisma/client';
import { PrismaNeon } from '@prisma/adapter-neon';
config({ path: '.env.local' }); config();
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL }) });
const rows = await prisma.photo.findMany({ select:{id:true,igAccount:true,width:true,lowRes:true,createdAt:true,shootKey:true,shootOrder:true} });
const w = rows.reduce((a,r)=>(a[r.width]=(a[r.width]||0)+1,a),{});
console.log('가로폭 분포:', Object.entries(w).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`${k}px:${v}`).join(' '));
console.log('lowRes 플래그:', rows.filter(r=>r.lowRes).length, '/', rows.length);
const batches = rows.reduce((a,r)=>{const k=r.createdAt.toISOString().slice(0,13);a[k]=(a[k]||0)+1;return a;},{});
console.log('\n수집 배치(시간대별):'); for(const [k,v] of Object.entries(batches).sort()) console.log('  ',k, v+'장');
const small = rows.filter(r=>r.width<=720);
console.log('\n720px 이하:', small.length, '| 그중 shootKey 있는', small.filter(r=>r.shootKey).length);
await prisma.$disconnect();
